[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.9.0"
rocket = "0.5.1"
serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.139"
ws = { package = "rocket_ws", version = "0.1.1" }
